# Generated by Django 3.0.4 on 2020-03-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability',
            field=models.ManyToManyField(to='accounts.Availability'),
        ),
    ]
