# Generated by Django 3.0.4 on 2020-03-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='avail_end',
            field=models.DateTimeField(null=True, verbose_name='Availability end time'),
        ),
        migrations.AddField(
            model_name='availability',
            name='avail_start',
            field=models.DateTimeField(null=True, verbose_name='Availability start time'),
        ),
    ]
