# Generated by Django 3.0.4 on 2020-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.ManyToManyField(blank=True, to='accounts.Availability'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='accounts.Specialty'),
        ),
    ]
